// Generated by gild-site/scripts/generate-api-client.mjs. Edit the site source.
/** Input boundaries used by both actual runner execution and import reports. */
const inputs:Record<string,string[]|null>={
  'actions/checkout':['fetch-depth','persist-credentials'],
  'actions/upload-artifact':null,'actions/cache':null,
  'actions/setup-node':['node-version','cache','cache-dependency-path'],
  'oven-sh/setup-bun':['bun-version'],
  'actions/setup-go':['go-version','cache','cache-dependency-path'],
  'dtolnay/rust-toolchain':['toolchain','components','targets'],
  'actions-rs/toolchain':['toolchain','components','targets','override','profile'],
}
export function actionSupport(uses:string,values:Record<string,unknown>) {
  const action=uses.split('@')[0].toLowerCase(),allowed=inputs[action],warnings:string[]=[]
  let error:string|undefined
  if(allowed===undefined)error=`gild doesn't run ${uses} yet`
  else if(allowed===null)warnings.push(`${action} is a no-op; artifact uploads and cache restoration are unsupported`)
  else {
    const unsupported=Object.keys(values).filter(key=>!allowed.includes(key))
    if(unsupported.length)error=`gild ${action==='actions/checkout'?'checkout':action} does not support: ${unsupported.join(', ')}`
    if((action==='dtolnay/rust-toolchain'||action==='actions-rs/toolchain') && (values.components||values.targets))error='gild toolchain checks do not support components or targets yet'
    if(action!=='actions/checkout' && action!=='actions/setup-node')warnings.push(`${action} checks tools already installed on the runner; tool downloads are unsupported`)
    if(values.cache)warnings.push('dependency cache options are a no-op on this machine')
  }
  return {error,warnings}
}
export const workflowKeys=['name','on','env','defaults','jobs','permissions']
export const jobKeys=['name','runs-on','needs','if','env','strategy','steps','timeout-minutes','defaults','permissions']
export const stepKeys=['id','name','run','uses','shell','working-directory','env','with','if','continue-on-error','timeout-minutes']
export const eventKeys=['push','pull_request','workflow_dispatch']
