// Generated by gild-site/scripts/generate-api-client.mjs. Edit the site source.
/** Shared by the site, API, renderer and generated CLI sources. */
export interface DisplayIdentity {
  id: string
  handle: string
  handle_verified: boolean
  kind: 'user' | 'org' | 'agent'
  owner?: { id: string; handle: string }
}
export interface IdentityAlias { org: string; id: string; alias: string }
export interface IdentityContext { orgs?: readonly string[]; aliases?: readonly IdentityAlias[] }
export function displayIdentity(identity: DisplayIdentity, context: IdentityContext = {}) {
  const aliases = (context.aliases ?? []).filter(a => a.id === identity.id && context.orgs?.includes(a.org))
  const alias = aliases[0]?.alias
  const collision = alias && (context.aliases ?? []).some(a => context.orgs?.includes(a.org) && a.alias === alias && a.id !== identity.id)
  const name = alias && !collision && aliases.every(a => a.alias === alias) ? alias : unicodeHandle(identity.handle)
  return (identity.kind === 'agent' ? '' : '@') + name
}
/** RFC 3492 decoding for presentation; storage validation remains node:url. */
export function unicodeHandle(handle: string) {
  return handle.split('.').map(label=>{
    if(!label.startsWith('xn--'))return label
    try {
      const input=label.slice(4),split=input.lastIndexOf('-'),out:number[]=split<0?[]:[...input.slice(0,split)].map(c=>c.codePointAt(0)!)
      let n=128,i=0,bias=72,index=split<0?0:split+1
      const adapt=(delta:number,points:number,first:boolean)=>{delta=first?Math.floor(delta/700):delta>>1;delta+=Math.floor(delta/points);let k=0;while(delta>455){delta=Math.floor(delta/35);k+=36}return k+Math.floor(36*delta/(delta+38))}
      while(index<input.length){const old=i;let weight=1
        for(let k=36;;k+=36){const code=input.charCodeAt(index++),digit=code>=48&&code<=57?code-22:code>=97&&code<=122?code-97:36;if(digit>=36)throw Error();i+=digit*weight;const t=k<=bias?1:k>=bias+26?26:k-bias;if(digit<t)break;weight*=36-t;if(!Number.isSafeInteger(i)||!Number.isSafeInteger(weight))throw Error()}
        const length=out.length+1;bias=adapt(i-old,length,old===0);n+=Math.floor(i/length);i%=length;out.splice(i,0,n);i++
      }
      return String.fromCodePoint(...out)
    }catch{return label}
  }).join('.')
}
export function participantDetail(identity: DisplayIdentity, org?: string) {
  return [unicodeHandle(identity.handle), identity.owner && `agent of @${unicodeHandle(identity.owner.handle)}`, org && `member of ${org}`, identity.handle_verified && 'verified'].filter(Boolean).join(' · ')
}
export function compareIdentities(a: DisplayIdentity, b: DisplayIdentity) {
  return Number(a.kind === 'agent') - Number(b.kind === 'agent') || a.handle.localeCompare(b.handle)
}
export function resolveMention(value: string, identities: readonly DisplayIdentity[], context: IdentityContext = {}) {
  const query = value.replace(/^@/, '').toLowerCase()
  const matches = identities.filter(i => i.handle === query || unicodeHandle(i.handle).toLowerCase()===query || displayIdentity(i, context).replace(/^@/, '').toLowerCase() === query)
  return matches.length === 1 ? matches[0] : null
}
export function identityPrefix(kind:DisplayIdentity['kind']) { return kind==='agent'?'':'@' }

/** Only public presentation fields may cross into page props. */
export function publicIdentity(identity: DisplayIdentity): DisplayIdentity {
  const {id,handle,handle_verified,kind,owner}=identity
  return {id,handle,handle_verified,kind,...(owner?{owner}: {})}
}
