// Generated by gild-site/scripts/generate-api-client.mjs. Edit the site source.
import { z } from 'zod'
const bounded = z.string().max(120).refine(s => !/[\x00-\x1f]/.test(s))
export const runtimeReport = z.strictObject({
  runtime: bounded,
  runtime_version: bounded.optional(),
  model: bounded.optional(),
  effort: bounded.optional(),
  isolation: z.enum(['vm', 'container', 'host', 'none']),
  host: bounded,
})
export const agentProfileInput = z.strictObject({
  display_name: z.string().min(1).max(80),
  role: z.string().max(280),
  preferences: z.strictObject({ runtime: z.enum(['claude', 'codex']).optional(), model: bounded.optional(), effort: bounded.optional() }),
})
export const agentProfile = agentProfileInput.extend({
  schema: z.literal(1),
  name: z.string().regex(/^[a-z0-9][a-z0-9-]{0,38}\/[a-z0-9][a-z0-9-]{0,30}$/),
  public_key: z.string().max(300).nullable(),
  avatar: z.string().regex(/^assets\/[a-f0-9]{64}\.png$/).nullable(),
  approved_by: z.string().nullable(),
  created_at: z.iso.datetime(),
  suspended_at: z.iso.datetime().nullable(),
  suspended_by: z.string().nullable(),
  revoked_at: z.iso.datetime().nullable(),
}).strict()
export const instructionsInput = z.strictObject({ text: z.string().max(65536), revision: z.string().regex(/^[a-f0-9]{64}$/) })
export const instructions = z.object({ text: z.string(), revision: z.string(), preferences: agentProfileInput.shape.preferences.optional(), history: z.array(z.object({ sha: z.string(), author: z.string(), at: z.string(), message: z.string() })) })
export const permissionInput = z.strictObject({ action: z.enum(['grants', 'suspend', 'resume', 'revoke']), grants: z.array(z.enum(['pr', 'review', 'queue'])).max(3).optional() }).refine(v => v.action !== 'grants' || v.grants !== undefined)
export const agentProfileView = z.object({
  profile: agentProfile,
  instructions,
  grants: z.array(z.string()),
  orchestrator: z.boolean(),
  tokens: z.array(z.object({ scopes: z.array(z.string()).nullable(), expires_at: z.string(), label: z.string() })),
  can_edit: z.boolean(),
  can_admin: z.boolean(),
  can_orchestrate: z.boolean(),
})
export const photoInput = z.strictObject({ data: z.string().max(350000) })
export type RepoAgentProfile = z.output<typeof agentProfile>
export const AGENT_PROFILE_OPERATIONS = ['migrateRepoAgentProfiles', 'repoAgentProfile', 'updateRepoAgentProfile', 'agentInstructions', 'updateAgentInstructions', 'updateAgentPhoto', 'deleteAgentPhoto', 'updateAgentPermissions'] as const
