// Generated by gild-site/scripts/generate-api-client.mjs. Edit the site source.
// Identity establishment precedes a gf_ token. These legacy browser/terminal
// routes keep their key-proof protocol and are deliberately outside API v1.
import { z } from 'zod'
import { ApiRequestError } from './client.ts'
const proof = z.object({
  challenge: z.string(),
  publicKey: z.string(),
  signature: z.string(),
})
export const bootstrapRoutes = {
  challenge: {
    path: '/api/auth/challenge',
    input: z.object({}),
    output: z.object({ challenge: z.string() }),
  },
  answer: {
    path: '/api/auth/answer',
    input: proof,
    output: z.object({ ok: z.boolean() }),
  },
  claim: {
    path: '/api/claim/answer',
    input: proof,
    output: z.object({ ok: z.boolean(), name: z.string() }),
  },
  token: {
    path: '/api/tokens',
    input: proof,
    output: z.object({ token: z.string(), name: z.string().nullable() }),
  },
  join: {
    path: '/api/agents/requests',
    input: z.object({
      sponsor: z.string(),
      label: z.string(),
      publicKey: z.string(),
      repo: z.string().optional(),
      grants: z.array(z.string()),
      note: z.string().optional(),
    }),
    output: z.object({
      id: z.string(),
      status: z.string(),
      agent: z.string(),
      approveUrl: z.string(),
      collect: z.string(),
    }),
  },
  collect: {
    path: '/api/agents/requests/{id}/token',
    input: z.object({ signature: z.string() }),
    output: z.object({
      status: z.string(),
      name: z.string().optional(),
      token: z.string().optional(),
      repo: z.string().nullable().optional(),
      grants: z.array(z.string()).optional(),
    }),
  },
} as const
export class ProofClient {
  constructor(
    readonly origin: string,
    readonly fetcher: typeof fetch = fetch,
  ) {}
  async request<I extends keyof typeof bootstrapRoutes>(
    id: I,
    input: z.input<(typeof bootstrapRoutes)[I]['input']>,
    params: Record<string, string> = {},
  ) {
    const route = bootstrapRoutes[id],
      path = route.path.replace(/\{(\w+)\}/g, (_, name) =>
        encodeURIComponent(params[name]),
      )
    const response = await this.fetcher(this.origin.replace(/\/$/, '') + path, {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify(route.input.parse(input)),
      redirect: 'error',
      signal: AbortSignal.timeout(30000),
    })
    const data = await response
      .json()
      .catch(() => ({ error: `HTTP ${response.status}` }))
    if (!response.ok)
      throw new ApiRequestError(
        response.status,
        data.message ?? data.error ?? `HTTP ${response.status}`,
      )
    return route.output.parse(data) as z.output<
      (typeof bootstrapRoutes)[I]['output']
    >
  }
}
