// Generated by gild-site/scripts/generate-api-client.mjs. Edit the site source.
import {
  routes,
  type Operation,
  type Input,
  type Output,
  type Query,
} from './contract.ts'
import { grantRequestHint } from './grant-request-contract.ts'
export class ApiRequestError extends Error {
  readonly status: number
  constructor(status: number, message: string) {
    super(message)
    this.status = status
  }
}
export class GildClient {
  constructor(
    readonly baseURL: string,
    readonly token: string,
    readonly fetcher: (
      input: RequestInfo | URL,
      init?: RequestInit,
    ) => Promise<Response> = fetch,
    readonly agentLabel?: string,
  ) {}
  async request<I extends Operation>(
    operation: I,
    params: Record<string, string | number> = {},
    body?: Input<I>,
    query?: Query<I>,
    options?: { idempotencyKey?: string; signal?: AbortSignal },
  ): Promise<Output<I>> {
    const route = routes.find((r) => r.id === operation)!
    const path = route.path.replace(/\{(\w+)\}/g, (_, name: string) => {
      if (params[name] === undefined)
        throw new Error(`Missing path parameter: ${name}`)
      const value = String(params[name])
      return name === 'path' || name === 'ref'
        ? value.split('/').map(encodeURIComponent).join('/')
        : encodeURIComponent(value)
    })
    const url = new URL(this.baseURL.replace(/\/$/, '') + path)
    if (query)
      for (const [name, value] of Object.entries(query))
        if (value !== undefined) url.searchParams.set(name, String(value))
    const res = await this.fetcher(url, {
      method: route.method,
      headers: {
        authorization: `Bearer ${this.token}`,
        'content-type': 'application/json',
        ...(options?.idempotencyKey
          ? { 'idempotency-key': options.idempotencyKey }
          : {}),
      },
      body: ['GET', 'DELETE'].includes(route.method)
        ? undefined
        : JSON.stringify(route.input.parse(body ?? {})),
      signal: options?.signal ?? AbortSignal.timeout(30000),
      redirect: 'error',
    })
    const data = res.status === 204 ? null : await res
      .json()
      .catch(() => ({ message: `HTTP ${res.status}` }))
    if (!res.ok) {
      let message=data.message ?? `HTTP ${res.status}`
      if(this.agentLabel && res.status===403 && /scope|grant/i.test(message) && params.owner && params.repo && ['repo:write','issues:write','pulls:write'].includes(route.scope??'')) {
        const grants=operation==='createReview'?'review':['mergePull','dequeuePull'].includes(operation)?'queue':'pr'
        message+=`\nRequest access: ${grantRequestHint(`${params.owner}/${params.repo}`,this.agentLabel,'gild',grants)}`
      }
      throw new ApiRequestError(
        res.status,
        message,
      )
    }
    return route.output.parse(data) as Output<I>
  }
}
// Protocol adapters still resolve through canonical definitions.
export async function requestPath(
  client: GildClient,
  method: string,
  path: string,
  body?: unknown,
) {
  for (const route of routes) {
    if (route.method !== method) continue
    const names = [...route.path.matchAll(/\{(\w+)\}/g)].map((m) => m[1]),
      pattern = new RegExp(
        '^' +
          route.path
            .split(/\{\w+\}/)
            .map((s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'))
            .join('([^/]+)') +
          '$',
      ),
      matched = pattern.exec(path)
    if (matched)
      return client.request(
        route.id,
        Object.fromEntries(
          names.map((n, i) => [n, decodeURIComponent(matched[i + 1])]),
        ),
        body as Input<Operation>,
      )
  }
  throw new Error(`Unknown API operation: ${method} ${path}`)
}
