// Generated by gild-site/scripts/generate-api-client.mjs. Edit the site source.
import { z } from 'zod'
export const environmentName = z.string().min(1).max(255).refine(n => !/[\x00-\x1f]/.test(n))
export const reviewer = z.object({ type: z.enum(['User', 'Agent']), login: z.string().regex(/^[a-z0-9][a-z0-9-]*(?:\/[a-z0-9][a-z0-9-]*)?$/i).toLowerCase() }).strict().refine(r => (r.type === 'Agent') === r.login.includes('/'), 'Agent identities must be owner/agent')
export const environmentConfig = z.object({
  reviewers: z.array(reviewer).max(64).default([]),
  wait_timer: z.number().int().min(0).max(43200).default(0),
  deployment_branch_policy: z.union([z.literal('any'), z.literal('main'), z.array(z.string().min(1).max(512)).min(1).max(256)]).default('any'),
  allowed_agents: z.array(z.string().regex(/^[a-z0-9][a-z0-9-]*\/[a-z0-9][a-z0-9-]*$/i).toLowerCase()).max(256).default([]),
}).strict()
export type EnvironmentConfig = z.infer<typeof environmentConfig>
export const environmentSchema = environmentConfig.extend({name:environmentName, id:z.number().int(), url:z.string(), html_url:z.string(), protection_rules:z.array(z.object({type:z.string()}).passthrough())})
export const deploymentSchema=z.object({id:z.number().int(),run:z.number().int(),environment:z.string(),ref:z.string(),sha:z.string(),actor:z.string(),status:z.string(),url:z.string().nullable(),created_at:z.string()})
export const pendingDeploymentSchema=z.object({job:z.number().int(),environment:z.object({id:z.number().int(),name:z.string()}),wait_timer:z.number(),wait_timer_started_at:z.string(),reviewers:z.array(reviewer),approved:z.array(z.string()),current_user_can_approve:z.boolean()})
