// Generated by gild-site/scripts/generate-api-client.mjs. Edit the site source.
import { z } from 'zod'
export const EVENT_NAMES = [
  'runner',
  'push',
  'pull_request',
  'pull_request_review',
  'pull_request_review_comment',
  'issues',
  'issue_comment',
  'workflow_run',
  'workflow_job',
  'ping',
  'merge_queue',
  'agent_request',
  'health_changed',
  'webhook_disabled',
] as const
export const eventName = z.enum(EVENT_NAMES)
export const hookInput = z.object({
  name: z.literal('web').default('web'),
  config: z.object({
    url: z.string().url(),
    content_type: z.enum(['json', 'form']).default('json'),
    secret: z.string().min(1).max(256),
    insecure_ssl: z.enum(['0']).default('0'),
  }),
  events: z.array(eventName).min(1).max(20).default(['push']),
  active: z.boolean().default(true),
})
export const hookPatch = z.object({
  config: hookInput.shape.config.partial().optional(),
  events: z.array(eventName).min(1).max(20).optional(),
  active: z.boolean().optional(),
})
export const hookSchema = z.object({
  id: z.number().int(),
  name: z.literal('web'),
  type: z.enum(['Repository', 'Organization']),
  active: z.boolean(),
  events: z.array(eventName),
  config: z.object({
    url: z.string(),
    content_type: z.enum(['json', 'form']),
    insecure_ssl: z.literal('0'),
  }),
  created_at: z.string(),
  updated_at: z.string(),
  url: z.string(),
  ping_url: z.string(),
  deliveries_url: z.string(),
  disabled_reason: z.string().nullable(),
})
export const streamEvent = z.object({
  id: z.string(),
  cursor: z.string(),
  event: eventName,
  repository: z.string().nullable(),
  created_at: z.string(),
  payload: z.record(z.string(), z.unknown()),
})
export const eventPage = z.object({
  events: z.array(streamEvent),
  cursor: z.string(),
})
export const deliverySchema = z.object({
  id: z.number().int().positive(),
  guid: z.string(),
  delivered_at: z.string().nullable(),
  redelivery: z.boolean(),
  duration: z.number(),
  status: z.string(),
  status_code: z.number().nullable(),
  event: eventName,
  action: z.string().nullable(),
  attempts: z.number().int(),
  request: z.object({
    headers: z.record(z.string(), z.string()),
    payload: z.record(z.string(), z.unknown()),
    wire: z.string(),
  }),
  response: z.object({
    headers: z.record(z.string(), z.string()),
    payload: z.string(),
    truncated: z.boolean(),
  }),
  error: z.string().nullable(),
})
export type HookInput = z.output<typeof hookInput>
export type HookPatch = z.output<typeof hookPatch>
export type Hook = z.output<typeof hookSchema>
export type StreamEvent = z.output<typeof streamEvent>
export type Delivery = z.output<typeof deliverySchema>
export interface Emission {
  id: string
  event: (typeof EVENT_NAMES)[number]
  repository: string | null
  audience?: string
  payload: Record<string, unknown>
}
