// Generated by gild-site/scripts/generate-api-client.mjs. Edit the site source.
import { z } from 'zod'
export const requestedGrant = z.enum(['pr', 'review', 'queue'])
export const grantRequestInput = z.strictObject({
  grants: z.array(requestedGrant).min(1).max(3),
  reason: z.string().trim().min(1).max(1000),
})
export const grantRequest = z.object({
  id: z.string(),
  agent: z.string(),
  repo: z.string(),
  grants: z.array(requestedGrant),
  reason: z.string(),
  status: z.enum(['pending', 'processing', 'approved', 'denied']),
  createdAt: z.string(),
  decidedAt: z.string().nullable(),
  decidedBy: z.string().nullable(),
  denialReason: z.string().nullable(),
})
export type GrantRequest = z.output<typeof grantRequest>
export const GRANT_REQUEST_OPERATIONS = [
  'requestAgentGrants',
  'repoGrantRequests',
  'grantRequest',
  'decideGrantRequest',
] as const
export function grantRequestHint(
  repo: string,
  agent: string,
  gild = 'gild',
  grants = '<grant>',
) {
  return `${gild} agent request-grants ${repo} --grants ${grants} --reason "<why this is needed>" --agent ${agent}`
}
export const GRANT_REQUEST_INSTRUCTION =
  'When a gild command fails for lack of a grant, request it with a reason using the command below instead of asking in chat. Wait for approval, then retry; your existing token works.'
