// Generated by gild-site/scripts/generate-api-client.mjs. Edit the site source.
import { z } from 'zod'
export const identitySchema = z.object({
  id:z.string(),kind:z.enum(['user','org','agent']),handle:z.string(),handle_verified:z.boolean(),
  placeholder:z.string(),label:z.string(),requested:z.string().nullable(),failures:z.number().int(),
  checked_at:z.number().nullable(),next_check:z.number(),owner:z.object({id:z.string(),handle:z.string()}).optional(),
  notifications:z.array(z.object({message:z.string(),created_at:z.number()})).optional(),
})
export const handleChallenge = z.object({id:z.string(),domain:z.string(),txt:z.object({name:z.string(),value:z.string()})})
export const handleHistory = z.object({history:z.array(z.object({handle:z.string(),changed_at:z.number(),expires_at:z.number().nullable(),reason:z.string()}))})
export const orgAliases = z.object({aliases:z.array(z.object({org:z.string(),id:z.string(),alias:z.string()}))})
