// Generated by gild-site/scripts/generate-api-client.mjs. Edit the site source.
import { z } from 'zod'
const text = z.string().max(65536), id = z.string().regex(/^[A-Za-z0-9_.:-]{1,160}$/)
const at = z.string().datetime(), number = z.number().int().positive().max(1_000_000_000)
export const provenance = z.object({ forge: z.enum(['github','gitlab']), url: z.string().url(), author: z.string().max(200), id, updatedAt: at, state:z.string().optional(),closedAt:at.nullable().optional(),mergedAt:at.nullable().optional() })
const base = { number, title: text, body: text, bodyParts:z.number().int().positive().max(128).optional(), createdAt: at, imported: provenance }
export const importRecord = z.discriminatedUnion('kind', [
  z.object({ kind:z.literal('issue'), ...base, state:z.enum(['open','closed']), labels:z.array(z.string().max(200)).max(100) }),
  z.object({ kind:z.literal('pull'), ...base, state:z.enum(['open','closed','merged']), head:z.string().max(300), base:z.string().max(300), sourceRef:z.string().max(300), labels:z.array(z.string().max(200)).max(100).optional(),sourceHead:z.object({ref:z.string(),sha:z.string().nullable(),repository:z.string().nullable()}).optional(), patchParts:z.number().int().nonnegative().optional(), merged:z.object({ by:text, at, commit:z.string().regex(/^[a-f0-9]{40}$/) }).optional() }),
  z.object({ kind:z.enum(['comment','review']), number, target:z.enum(['issue','pr']), id, body:text, bodyParts:z.number().int().positive().max(128).optional(), createdAt:at, imported:provenance, verdict:z.enum(['approve','changes','comment']).optional(), headOid:z.string().nullable().optional(), path:text.optional(), line:z.number().int().optional(), side:z.enum(['LEFT','RIGHT']).optional() }),
  z.object({ kind:z.literal('label'), id, name:z.string().max(200), color:z.string().max(10), description:text }),
  z.object({kind:z.literal('body'),number,target:z.enum(['issue','pr']),record:z.enum(['issue','pull','comment','review']),id:id.optional(),createdAt:at,version:at,part:z.number().int().nonnegative().max(127),parts:z.number().int().positive().max(128),text:z.string().max(8192)}),
  z.object({ kind:z.literal('patch'), number, part:z.number().int().nonnegative().max(100000), text:z.string().max(16384) }),
])
export type ImportRecord = z.infer<typeof importRecord>
export const importInput = z.object({ url:z.string().min(1).max(2048), name:z.string().regex(/^[a-z0-9][a-z0-9._-]{0,62}$/i).optional(), private:z.boolean().optional(), mirror:z.boolean().default(false), source_token:z.string().max(16384).optional(), forge:z.enum(['github','gitlab','git']).optional() })
export const importProgress = z.object({ phase:z.enum(['git','metadata','workflows']), completed:z.number().int().nonnegative(), message:z.string().max(200), checkpoint:z.string().max(2048).optional() })
export const importSummary=z.object({branches:z.number().int().nonnegative(),tags:z.number().int().nonnegative(),commits:z.number().int().nonnegative(),records:z.number().int().nonnegative(),elapsed_ms:z.number().nonnegative()})
export const importStatus = z.object({ repository:z.string(), source:z.string(), mirror:z.boolean(), state:z.enum(['queued','running','complete','mirroring','failed','cutover']), progress:importProgress, warnings:z.array(z.string()), error:z.string().nullable(), updated_at:z.string(), next_sync:z.string().nullable(),summary:importSummary.optional() })
export const importAssignment = z.object({ repository:z.string(), source:z.string(), forge:z.enum(['github','gitlab','git']), token:z.string(), source_token:z.string().optional(), mirror:z.boolean(), checkpoint:z.string() })
export const importCredentials = z.object({ url:z.string(), token:z.string() })
export const importBatch = z.object({ records:z.array(importRecord).max(40), progress:importProgress })
