// Generated by gild-site/scripts/generate-api-client.mjs. Edit the site source.
import { z } from 'zod'
// Orchestrator agents: a grant on a repo or org lets an agent spawn child
// agents there, suspend and resume them, and read every agent's mentions.
const text = z.string()
export const agentGrant = z.enum(['pr', 'review', 'queue'])
export const orchestratorGrant = z.object({
  agent: text,
  /** Where the grant lives: this repo, or the org that owns it. */
  scope: z.enum(['repo', 'org']),
  child_limit: z.number().int(),
  /** Live (not revoked) children it holds, across every repo. */
  children: z.number().int(),
  granted_by: text,
  granted_at: text,
})
export const orchestratorList = z.object({
  orchestrators: z.array(orchestratorGrant),
})
export const orchestratorInput = z.object({
  /** sponsor/label of an existing agent (an unknown one answers 404). */
  agent: text.min(1).max(80),
  child_limit: z.number().int().min(1).max(100).default(10),
})
export const orchestratorRevoked = z.object({
  ok: z.literal(true),
  agent: text,
  /** Every descendant revoked with it. */
  revoked: z.array(text),
})
export const childInput = z.object({
  label: text.regex(/^[a-z0-9][a-z0-9-]{0,30}$/),
  publicKey: text.regex(/^ed25519:[A-Za-z0-9+/=]{1,200}$/),
  grants: z.array(agentGrant).max(3).default([]),
  note: text.max(280).optional(),
})
export const childAgent = z.object({
  name: text,
  label: text,
  /** The orchestrator that spawned it. */
  sponsor: text,
  /** The person behind the orchestrator, and so behind the child. */
  human: text,
  repo: text,
  grants: z.array(agentGrant),
  suspended: z.boolean(),
  suspended_at: text.nullable(),
  suspended_by: text.nullable(),
  created_at: text,
  revoked_at: text.nullable(),
})
export const spawnedChild = childAgent.extend({
  request_id: text,
  scopes: z.array(text),
  /** Returned once; the server keeps only its hash. */
  token: text,
})
export const suspension = z.object({
  agent: text,
  suspended: z.boolean(),
  suspended_at: text.nullable(),
  suspended_by: text.nullable(),
})
export type ChildAgent = z.output<typeof childAgent>
/** Agent-facing operations: no token scope, the orchestrator grant (or a
 *  person's repo admin) is checked by the orchestrator service itself. */
export const ORCHESTRATED_OPERATIONS = ['childAgents', 'createChildAgent', 'suspendAgent', 'resumeAgent'] as const
/** Every operation the orchestrator service executes. */
export const ORCHESTRATOR_OPERATIONS = [
  ...ORCHESTRATED_OPERATIONS,
  'repoOrchestrators', 'setRepoOrchestrator', 'deleteRepoOrchestrator',
  'orgOrchestrators', 'setOrgOrchestrator', 'deleteOrgOrchestrator',
] as const
