// Generated by gild-site/scripts/generate-api-client.mjs. Edit the site source.
import { z } from 'zod'
export const runnerRegistration = z.object({
  name: z.string().regex(/^[a-zA-Z0-9][\w.-]{0,63}$/),
  os: z.enum(['darwin', 'macos', 'linux', 'windows', 'win32']),
  arch: z.enum(['x64', 'arm64', 'aarch64', 'amd64']),
  labels: z
    .array(z.string().regex(/^[\w.-]{1,64}$/))
    .max(32)
    .default([]),
  group: z.string().min(1).default('default'),
})
export const runnerGroup = z.object({
  id: z.string().min(1),
  name: z.string().trim().min(1).max(64),
  visibility: z.enum(['all', 'selected']),
  allow_public_repositories: z.boolean(),
  repositories: z
    .array(z.string().regex(/^[a-zA-Z0-9][\w.-]*\/[a-zA-Z0-9][\w.-]*$/))
    .max(1000),
})
export const groupInput = runnerGroup
  .omit({ id: true })
  .partial()
  .extend({ name: runnerGroup.shape.name })
