// Generated by gild-site/scripts/generate-api-client.mjs. Edit the site source.
export const SCOPES = [
  'repo:read',
  'repo:write',
  'issues:write',
  'pulls:write',
  'actions',
  'hooks',
  'agents',
  'admin',
] as const
export type Scope = (typeof SCOPES)[number]
export interface Principal {
  anonymous?: boolean
  id: string
  name: string
  publicKey: string
  scopes: readonly string[] | null
  repos: readonly string[] | null
}
export function hasScope(p: Principal, scope: Scope) {
  return p.scopes === null || p.scopes.includes(scope)
}
export function permitsRepo(p: Principal, owner: string, repo: string) {
  return (
    p.repos === null ||
    p.repos.some((r) => r.toLowerCase() === `${owner}/${repo}`.toLowerCase())
  )
}
export function grantScopes(grants: readonly string[]): Scope[] {
  return [
    'repo:read',
    ...(grants.includes('pr')
      ? (['repo:write', 'issues:write', 'pulls:write'] as const)
      : []),
    ...(grants.includes('review') || grants.includes('queue')
      ? (['pulls:write'] as const)
      : []),
  ]
}
