// Generated by gild-site/scripts/generate-api-client.mjs. Edit the site source.
import { z } from 'zod'
const path = z
  .string()
  .min(1)
  .max(1024)
  .refine(
    (p) =>
      !p.startsWith('/') &&
      !p.split('/').includes('..') &&
      !/[\x00-\x1f]/.test(p),
    'Use a repository-relative path',
  )
export const sessionInput = z
  .object({
    id: z.string().uuid().optional(),
    agent: z.string().max(100).optional(),
    started_at: z.iso.datetime(),
    ended_at: z.iso.datetime().nullable().default(null),
    model: z.string().min(1).max(120),
    tokens_in: z.number().int().nonnegative().default(0),
    tokens_out: z.number().int().nonnegative().default(0),
    cost: z.number().nonnegative().optional(),
    currency: z
      .string()
      .regex(/^[A-Z]{3}$/)
      .default('USD'),
    commands: z
      .array(
        z.object({
          name: z.string().min(1).max(4096),
          exit_code: z.number().int().nullable(),
          duration_ms: z.number().nonnegative(),
        }),
      )
      .max(200)
      .default([]),
    files: z
      .object({
        read: z.array(path).max(1000).default([]),
        written: z.array(path).max(1000).default([]),
      })
      .default({ read: [], written: [] }),
    notes: z.string().max(16000).default(''),
  })
  .refine(
    (s) => !s.ended_at || Date.parse(s.ended_at) >= Date.parse(s.started_at),
    'ended_at must follow started_at',
  )
export const receiptPayload = sessionInput.safeExtend({
  id: z.string().uuid(),
  agent: z.string(),
  repository: z.string(),
  target: z.string(),
  created_at: z.iso.datetime(),
  updated_at: z.iso.datetime(),
  version: z.number().int().positive(),
  closed: z.boolean(),
})
export const receiptSchema = receiptPayload.safeExtend({
  reported_by: z.literal('agent').default('agent'),
})
export type SessionInput = z.output<typeof sessionInput>
export type Receipt = z.output<typeof receiptSchema>
