// Generated by gild-site/scripts/generate-api-client.mjs. Edit the site source.
import { z } from 'zod'
const link = z.union([
  z.literal(''),
  z
    .url()
    .max(2048)
    .refine((s) => /^https?:\/\//.test(s), 'Use an http or https URL'),
])
const email = z.union([z.literal(''), z.email().max(254)])
export const profileSchema = z.object({
  displayName: z.string().max(100),
  publicEmail: email,
  description: z.string().max(1000),
  url: link,
  socialLinks: z.array(link).max(4),
  location: z.string().max(100),
  picture: z.string().nullable(),
})
export const profileInput = profileSchema
  .omit({ picture: true })
  .partial()
  .strict()

export const renameStatus = z.object({
  job: z
    .object({
      id: z.string(),
      from: z.string(),
      to: z.string(),
      org: z.boolean(),
      orgOwner: z.boolean(),
      phase: z.enum([
        'waiting',
        'copying',
        'publishing',
        'rebinding',
        'rollback',
        'complete',
        'failed',
      ]),
      repos: z.array(
        z.object({ from: z.string(), to: z.string(), id: z.string() }),
      ),
      copied: z.number(),
      rebound: z.number(),
      error: z.string().nullable(),
    })
    .nullable(),
})
