// Generated by gild-site/scripts/generate-api-client.mjs. Edit the site source.
import { isIP } from 'node:net'
import { publicAddress } from '../public-address.ts'
import type { ImportRecord } from '../api/import-contract.ts'
export type Forge = 'github' | 'gitlab' | 'git'
export interface Source { url:string; forge:Forge; project:string; api:string; name:string }
export function sourceURL(input:string, forge?:Forge):Source {
  if (/^git@[^:]+:.+/.test(input)) input='ssh://'+input.replace(':','/')
  const u=new URL(input)
  if (!['https:','http:','ssh:'].includes(u.protocol) || u.password || (u.username && !(u.protocol==='ssh:' && u.username==='git')) || u.search || u.hash)
    throw Error('Use a Git HTTP(S) or SSH URL without embedded credentials')
  if(isIP(u.hostname.replace(/^\[|\]$/g,'')) && !publicAddress(u.hostname)) throw Error('Use a public forge hostname')
  if (!u.hostname || /^(localhost|.*\.localhost|.*\.local|127\..*|0\.0\.0\.0|\[.*\])$/i.test(u.hostname)) throw Error('Use a public forge hostname')
  const project=u.pathname.replace(/^\/+|\/+$/g,'').replace(/\.git$/,'')
  if (!project || project.split('/').some(p=>!p || p==='..' || p==='.' || !/^[\w.~-]+$/.test(p))) throw Error('Invalid source repository path')
  forge ??= u.hostname==='github.com'?'github':u.hostname==='gitlab.com'?'gitlab':'git'
  if (forge==='github' && u.hostname!=='github.com') throw Error('GitHub metadata currently requires github.com')
  if (forge==='github' && project.split('/').length!==2) throw Error('Use a GitHub owner/repository URL')
  const api=forge==='github'?`https://api.github.com/repos/${project}`:(u.protocol==='ssh:'?`https://${u.host}`:u.origin)+`/api/v4/projects/${encodeURIComponent(project)}`
  return { url:u.toString().replace(/\/$/,''),forge,project,api,name:project.split('/').at(-1)! }
}
export function importedAuthor(forge:Forge, login:string) { return `${forge}:${login || 'ghost'}` }
export function authorLabel(author:string) {
  const match=/^(github|gitlab):(.*)$/.exec(author)
  return match?`imported from @${match[2]} on ${match[1]==='github'?'GitHub':'GitLab'}`:`@${author}`
}
export function mappedNumber(forge:Forge, kind:'issue'|'pull', n:number) { return forge==='gitlab'?n*2-(kind==='issue'?1:0):n }
export function rewriteLinks(body:string, source:Source, destination:string) {
  const escape=(s:string)=>s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')
  const u=new URL(source.url),web=`${u.protocol==='ssh:'?'https:':u.protocol}//${u.host}/${source.project}`
  return body.replace(new RegExp(escape(web)+(source.forge==='gitlab'?'/-/':'/')+'(issues|pull|merge_requests)/(\\d+)(#[^\\s)]+)?','g'),(_all,kind,n,anchor)=>`${destination}/${kind==='issues'?'issues':'pulls'}/${mappedNumber(source.forge,kind==='issues'?'issue':'pull',Number(n))}${anchor??''}`)
}
export interface SourceOptions {
  source:Source; token?:string; destination:string; checkpoint?:string;
  fetcher?:(input:RequestInfo|URL,init?:RequestInit)=>Promise<Response>; signal?:AbortSignal;
  head(ref:string, number:number):Promise<string|null>;
  branch?(ref:string):string;
}
export interface SourceEvent { records:ImportRecord[]; checkpoint?:string }
/** Page boundaries are explicit; a interrupted item replays deterministic IDs.
 * REST credentials go only to the source API, never to pagination links. */
async function* metadataRecords(options:SourceOptions):AsyncGenerator<SourceEvent> {
  const {source,token,destination}=options, fetcher=options.fetcher??fetch
  if(source.forge==='git') return
  const gh=source.forge==='github'
  const headers:Record<string,string>={'accept':'application/json','user-agent':'gild-import'}
  if(token) headers[gh?'authorization':'private-token']=gh?`Bearer ${token}`:token
  if(gh) {headers.accept='application/vnd.github+json';headers['X-GitHub-Api-Version']='2026-03-10'}
  const request=async(path:string,accept?:string)=>{
    let url=new URL(source.api+path)
    const origin=url.origin
    for(let redirects=0;redirects<=3;redirects++) {
      const response=await fetcher(url.toString(),{headers:{...headers,...(accept?{accept}:{})},redirect:'error',signal:options.signal?AbortSignal.any([options.signal,AbortSignal.timeout(60000)]):AbortSignal.timeout(60000)})
      if([301,302,307,308].includes(response.status)) {
        const location=response.headers.get('location')
        await response.body?.cancel()
        if(!location)throw Error('Source API redirect has no destination')
        const next=new URL(location,url)
        if(next.origin!==origin || next.username || next.password || !(gh ? /^\/(?:repos|repositories)\//.test(next.pathname) : next.pathname.startsWith('/api/v4/')))throw Error('Source API redirect must stay on the same forge API origin')
        url=next;continue
      }
      if(!response.ok) throw Error(`Source API ${response.status}; import can be resumed after checking access or rate limits`)
      return response
    }
    throw Error('Source API redirect limit exceeded')
  }
  const json=async(path:string):Promise<any>=> (await request(path)).json()
  const page=async(path:string,n:number):Promise<any[]>=>json(`${path}${path.includes('?')?'&':'?'}per_page=30&page=${n}`)
  const projects=new Map([[source.project,source]])
  const body=(v:unknown)=>{let text=typeof v==='string'?v:'';for(const project of projects.values())text=rewriteLinks(text,project,destination);return text}
  const provenance=(x:any,id:string)=>{
    const link=x.html_url??x.web_url
    if(link){const web=new URL(link),project=(gh?/^\/([^/]+\/[^/]+)\/(?:issues|pull)\//:/^\/(.+)\/-\/(?:issues|merge_requests)\//).exec(web.pathname)?.[1];if(project && web.host===new URL(source.url).host)projects.set(project,{...source,project,url:web.origin+'/'+project})}
    return {forge:source.forge as 'github'|'gitlab',url:x.html_url??x.web_url??`https://${new URL(source.url).hostname}/${source.project}`,author:x.user?.login??x.author?.username??'ghost',id,updatedAt:x.updated_at??x.submitted_at??x.created_at,state:x.state,closedAt:x.closed_at,mergedAt:x.merged_at}}
  let resume:{stage:number;page:number;index:number}={stage:0,page:1,index:0}
  if(options.checkpoint) {
    resume=JSON.parse(options.checkpoint)
    if(![resume.stage,resume.page,resume.index].every(Number.isSafeInteger) || resume.stage<0 || resume.stage>3 || resume.page<1 || resume.index<0 || resume.index>30) throw Error('Invalid import checkpoint')
  }
  const lists=gh?['/labels','/issues?state=all&sort=created&direction=asc','/pulls?state=all&sort=created&direction=asc']:['/labels','/issues?scope=all&state=all&order_by=created_at&sort=asc','/merge_requests?scope=all&state=all&order_by=created_at&sort=asc']
  for(let stage=resume.stage;stage<lists.length;stage++) {
    for(let p=stage===resume.stage?resume.page:1;;p++) {
      const rows=await page(lists[stage],p)
      if(!rows.length) break
      for(let i=stage===resume.stage && p===resume.page?resume.index:0;i<rows.length;i++) {
        let x=rows[i]
        if(stage===0) {
          yield {records:[{kind:'label',id:String(x.id),name:x.name,color:String(x.color??'').replace(/^#/,''),description:x.description??''}]}
        } else if(!(gh && stage===1 && x.pull_request)) {
          const kind=stage===1?'issue':'pull', original=gh?x.number:x.iid,n=mappedNumber(source.forge,kind,original)
          const path=gh?`/${kind==='issue'?'issues':'pulls'}/${original}`:`/${kind==='issue'?'issues':'merge_requests'}/${original}`
          if(kind==='pull') x=await json(path)
          const imported=provenance(x,`${kind}:${original}`), createdAt=x.created_at
          if(x.milestone) yield {records:[{kind:'label',id:`milestone:${x.milestone.id}`,name:`milestone:${x.milestone.title}`,color:'ededed',description:x.milestone.description??''}]}
          if(kind==='issue') {
            yield {records:[{kind,number:n,title:x.title,body:body(x.body??x.description),createdAt,imported,state:x.state==='opened'||x.state==='open'?'open':'closed',labels:[...(x.labels??[]).map((l:any)=>typeof l==='string'?l:l.name),...(x.milestone?[`milestone:${x.milestone.title}`]:[])]}]}
          } else {
            const pullLabels=[...(x.labels??[]).map((l:any)=>typeof l==='string'?l:l.name),...(x.milestone?[`milestone:${x.milestone.title}`]:[])]
            const sourceHead={ref:gh?x.head?.ref??'':x.source_branch??'',sha:gh?x.head?.sha??null:x.sha??null,repository:gh?x.head?.repo?.full_name??null:x.source_project_id?String(x.source_project_id):null}
            const pullBase=options.branch?.(gh?x.base.ref:x.target_branch)??(gh?x.base.ref:x.target_branch)
            const sourceRef=gh?`refs/pull/${original}/head`:`refs/merge-requests/${original}/head`
            const head=await options.head(sourceRef,n)
            const state=head?(x.merged_at || x.state==='merged'?'merged':x.state==='open'||x.state==='opened'?'open':'closed'):'closed'
            yield {records:[{kind,number:n,title:x.title,body:body(x.body??x.description),createdAt,imported,state,head:head??`import/missing/${n}`,base:pullBase,sourceRef,labels:pullLabels,sourceHead,...(x.merge_commit_sha && x.merged_at?{merged:{by:importedAuthor(source.forge,gh?x.merged_by?.login:x.merge_user?.username),at:x.merged_at,commit:x.merge_commit_sha}}:{})}]}
            // Store patches in bounded chunks, including for merged/deleted heads.
            if(!head) {
              let parts=0
              if(gh) {
                const response=await request(path,'application/vnd.github.patch'),reader=response.body!.pipeThrough(new TextDecoderStream()).getReader()
                let buffer=''
                for(;;) {
                  const {value,done}=await reader.read();buffer+=value??''
                  while(buffer.length>=8192) { yield {records:[{kind:'patch',number:n,part:parts++,text:buffer.slice(0,8192)}]};buffer=buffer.slice(8192) }
                  if(done) break
                }
                if(buffer) yield {records:[{kind:'patch',number:n,part:parts++,text:buffer}]}
              } else {
                for(let dp=1;;dp++) {
                  const diffs=await page(path+'/diffs',dp)
                  if(!diffs.length) break
                  for(const diff of diffs) {
                    if(diff.collapsed || diff.too_large) throw Error('GitLab omitted a patch; retry with its head ref available')
                    const patch=`diff --git a/${diff.old_path} b/${diff.new_path}\n--- ${diff.new_file?'/dev/null':'a/'+diff.old_path}\n+++ ${diff.deleted_file?'/dev/null':'b/'+diff.new_path}\n${diff.diff}`
                    for(let at=0;at<patch.length;at+=8192) yield {records:[{kind:'patch',number:n,part:parts++,text:patch.slice(at,at+8192)}]}
                  }
                }
              }
              yield {records:[{kind,number:n,title:x.title,body:body(x.body??x.description),createdAt,imported,state:'closed',head:`import/missing/${n}`,base:pullBase,sourceRef,labels:pullLabels,sourceHead,patchParts:parts}]}
            }
          }
          const commentsPath=gh?`/issues/${original}/comments`:path+(kind==='pull'?'/discussions':'/notes')
          for(let cp=1;;cp++) {
            const comments=await page(commentsPath,cp)
            if(!comments.length) break
            for(const c of (!gh && kind==='pull'?comments.flatMap(d=>d.notes??[]):comments)) {
              const verdict=!gh && kind==='pull' && c.system?(c.body==='approved this merge request'?'approve':c.body?.includes('requested changes')?'changes':undefined):undefined
              yield {records:[{kind:verdict?'review':'comment',number:n,target:kind==='issue'?'issue':'pr',id:`note:${c.id}`,body:body(c.body),createdAt:c.created_at,imported:provenance(c,`note:${c.id}`),...(verdict?{verdict}:{}),...(c.position?{path:c.position.new_path??c.position.old_path,...(c.position.new_line??c.position.old_line?{line:c.position.new_line??c.position.old_line}:{}),side:c.position.new_line?'RIGHT':'LEFT',headOid:c.position.head_sha??null}:{})}]}
            }
            if(comments.length<30) break
          }
          if(gh && kind==='pull') {
            for(const [suffix,review] of [['reviews',true],['comments',false]] as const) {
              for(let cp=1;;cp++) {
                const entries=await page(path+'/'+suffix,cp)
                if(!entries.length) break
                for(const c of entries) {
                  if(!c.submitted_at && review) continue // Unsubmitted draft reviews are private.
                  yield {records:[{kind:review?'review':'comment',number:n,target:'pr',id:`${suffix}:${c.id}`,body:body(c.body),createdAt:c.submitted_at??c.created_at,imported:provenance(c,`${suffix}:${c.id}`),...(review?{verdict:c.state==='APPROVED'?'approve':c.state==='CHANGES_REQUESTED'?'changes':'comment',headOid:c.commit_id??null}:{path:c.path,...(c.line || c.original_line?{line:c.line??c.original_line}:{}),side:c.side??'RIGHT'})}]}
                }
                if(entries.length<30) break
              }
            }
          }
        }
        yield {records:[],checkpoint:JSON.stringify({stage,page:p,index:i+1})}
      }
      if(rows.length<30) break
    }
  }
  yield {records:[],checkpoint:JSON.stringify({stage:3,page:1,index:0})}
}

/** GitLab allows descriptions up to 1 MiB. Large bodies travel as bounded
 * records and materialize only after their final deterministic chunk. */
export async function* metadata(options:SourceOptions):AsyncGenerator<SourceEvent> {
  for await (const event of metadataRecords(options)) {
    for(const record of event.records) {
      if('body' in record && record.body.length>32768) {
        if(record.body.length>1_048_576)throw Error('Source body exceeds the forge description limit')
        const text=record.body,parts=Math.ceil(text.length/8192)
        yield {records:[{...record,body:'',bodyParts:parts}]}
        for(let part=0;part<parts;part++)yield {records:[{kind:'body',number:record.number,target:record.kind==='issue'?'issue':record.kind==='pull'?'pr':record.target,record:record.kind,...('id' in record?{id:record.id}:{}),createdAt:record.createdAt,version:record.imported.updatedAt,part,parts,text:text.slice(part*8192,(part+1)*8192)}]}
      } else yield {records:[record]}
    }
    if(event.checkpoint!==undefined)yield {records:[],checkpoint:event.checkpoint}
  }
}
