// Generated by gild-site/scripts/generate-api-client.mjs. Edit the site source.
import { z } from 'zod'
import { sessionState } from '../api/sessions-contract.ts'
export const channelState = sessionState
export type ChannelState = z.output<typeof channelState>
export function stateLabel(state: ChannelState) {
  if (state.status === 'waiting') return '◐ waiting'
  if (state.status === 'busy' || state.status === 'tool_start') return '● busy' + (state.tool ? ` · ${state.tool}` : '')
  if (['idle', 'tool_end', 'ended'].includes(state.status)) return '○ idle'
  return '○ unknown'
}
