// Generated by gild-site/scripts/generate-api-client.mjs. Edit the site source.
import { isIP } from 'node:net'
export function publicAddress(address: string) {
  const ip = address.replace(/^\[|\]$/g, '').toLowerCase()
  if (isIP(ip) === 4) {
    const [a, b, c] = ip.split('.').map(Number)
    return !(
      a === 0 ||
      a === 10 ||
      a === 127 ||
      a >= 224 ||
      (a === 169 && b === 254) ||
      (a === 172 && b >= 16 && b <= 31) ||
      (a === 192 &&
        (b === 168 || b === 0 || b === 2 || (b === 88 && c === 99))) ||
      (a === 100 && b >= 64 && b <= 127) ||
      (a === 198 && (b === 18 || b === 19 || (b === 51 && c === 100))) ||
      (a === 203 && b === 0 && c === 113)
    )
  }
  // Only global unicast IPv6. Excludes mapped IPv4, NAT64, loopback,
  // link-local, ULA, multicast, documentation, Teredo and 6to4 tunnels.
  if (isIP(ip) === 6) {
    const normalized = new URL(`http://[${ip}]/`).hostname.slice(1, -1)
    const [prefix, suffix] = normalized.split(':'),
      first = parseInt(prefix, 16),
      second = parseInt(suffix || '0', 16)
    return (
      first >= 0x2000 &&
      first < 0x3fff &&
      !(first === 0x2001 && (second < 0x200 || second === 0xdb8)) &&
      first !== 0x2002
    )
  }
  return false
}
